version: '3'
services:
  short-url-mysql:
    image: 'mysql:5.7.25'
    environment:
      - MYSQL_ROOT_PASSWORD=shorturl_pw
      - MYSQL_DATABASE=short_url_db
    ports:
      - '3306:3306'

  short-url-backend:
    build: .
    ports:
      - '80:80'
