FROM php:7.3.3-cli-stretch

#utils
RUN apt-get update
RUN apt-get install --yes curl wget htop
RUN apt-get install --yes libzip-dev

# php exts
RUN apt-get install -y zlib1g-dev && docker-php-ext-install zip && docker-php-ext-install bcmath && docker-php-ext-install mysqli && docker-php-ext-install pdo_mysql


RUN wget https://getcomposer.org/installer
RUN php installer --install-dir /usr/bin/
RUN apt-get install --yes git

COPY ./ .
RUN composer.phar install
RUN cp .env.example .env
RUN php artisan key:generate

ENTRYPOINT ["php", "vendor/bin/phpunit"]
